services:
  bot:
    build: .
    image: 'moex-currency-bot'
    container_name: 'moex-currency-bot'
    restart: unless-stopped
    env_file:
      - './config/bot.env'
    volumes:
      - './certs/cert.pem:/certs/cert.pem:ro'
      - './config/config.toml:/config/config.toml:ro'
    networks:
      - 'nginx-network'
    expose:
      - '8000'

  nginx:
    image: nginx:latest
    container_name: 'nginx'
    restart: unless-stopped
    ports:
      - '443:443'
    volumes:
      - './config/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './certs/:/certs/:ro'
    networks:
      - 'nginx-network'

networks:
  nginx-network:
    driver: bridge
