MoexIssURL = "https://iss.moex.com/iss/engines/currency/markets/selt/boards/CETS/securities.json"
OrderBookDepth = 10
RateDP = 4
ConvNominalBYN = 100.0

[bot]
Polling = true
PollingTimeout = 10
Private = true
ChatIDs = []
HttpTimeout = 10
OrderBookUpdateInterval = 60
MoexIssUpdateInterval = 300
WelcomeMsg = "Welcome!"

Name = "Rate MOEX [🇷🇺]"
About = "MOEX Currency Exchange Rates"
Description = """
MOEX Currency Exchange Rates

Try these:
/rates - Rates
/ratesconv - Rates Conv"""

[bot.webhook]
Url = "https://<HOST>/moex-currency-bot/webhook"
Port = 8000
Cert = "./certs/cert.pem"
