[bot]
Polling = true
PollingTimeout = 10
Private = true
ChatIDs = []
HttpTimeout = 10
RatesUpdateInterval = 60
MoexIssUpdateInterval = 300
WelcomeMsg = "Welcome!"

[bot.webhook]
Url = "https://<HOST>/moex-currency-bot/webhook"
Port = 8000
Cert = "./certs/cert.pem"
