[bot]
Polling = true
PollingTimeout = 10
Private = true
ChatIDs = []
HttpTimeout = 10
RatesUpdateInterval = 60
MoexIssUpdateInterval = 300
WelcomeMsg = "Welcome!"

Name = "Rate MOEX [🇷🇺]"
About = "MOEX Currency Exchange Rates"
Description = """
MOEX Currency Exchange Rates

Try these:
/rates - Get Rates
/ratesconv - Get Rates Conv"""

[bot.webhook]
Url = "https://<HOST>/moex-currency-bot/webhook"
Port = 8000
Cert = "./certs/cert.pem"

[gen]
RateDP = 4
