[bot]
Polling = true
PollingTimeout = 10
Private = true
ChatIds = []
UpdateInterval = 60
WelcomeMsg = "Welcome!"

[bot.webhook]
Url = "https://<HOST>/moex-currency-bot/webhook/"
Port = 8000
Cert = "./certs/cert.pem"
